### ISSUE TITLE
Implement cmd-cluster-info-k8s application

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/cmd-cluster-info-k8s#1]
##Problem

We should add a possible for users to select nses from the different clusters in interdomain scenarious.

## Solution

Add a new cmd-cluster-info-k8s application that will configure nsmgr-proxy with cluster labels.

Cluster labels are planned to get from the CRD ClusterProperty.

## TODO

- [ ] Add clusterinfo chain element into sdk
- [ ] Add ClusterProperty support into sdk-k8s
- [ ] Implement clusterinfo application
- [ ] Add integration test
